before_cache:
- rm -rf $HOME/CACHE; find $TRAVIS_BUILD_DIR -name .starts | while read line; do du
  -sh $line;         DIR=$(dirname $HOME/CACHE$line); mkdir -p $DIR; cp -r $line $DIR;
  done
- find $TRAVIS_BUILD_DIR -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  $HOME/CACHE$line); mkdir -p $DIR; cp -r $line $DIR; done
- echo CACHESIZE $(du -sk $HOME/CACHE)
before_install:
- find $HOME/CACHE -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#jdeps-cache/} ]]; then cp -r $line $DIR; fi;
  done
- find $HOME/CACHE -name .starts | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.starts/} ]]; then cp -r $line $DIR; fi; done
- grep -q -z '<artifactId>killbill-oss-parent</artifactId>[[:space:]]\+<groupId>org.kill-bill.billing</groupId>[[:space:]]\+<version>[0-9\.]*-SNAPSHOT</version>'
  pom.xml && echo "killbill-oss-parent SNAPSHOT has been found, exiting." && exit
  0 || true
- echo "<settings><profiles><profile><repositories><repository><id>central</id><name>bintray</name><url>http://jcenter.bintray.com</url></repository></repositories><id>bintray</id></profile></profiles><activeProfiles><activeProfile>bintray</activeProfile></activeProfiles></settings>"
  > /var/tmp/settings.xml
- "function keep_alive() {\n  while true; do\n    echo -en \"\\a\"\n    sleep 5\n\
  \  done\n}\nkeep_alive &\n"
before_script:
- find $TRAVIS_BUILD_DIR -name .starts | while read line; do rm -rf $line; done
- find $TRAVIS_BUILD_DIR -name jdeps-cache | while read line; do rm -rf $line; done
- find $HOME/CACHE -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#jdeps-cache/} ]]; then cp -r $line $DIR; fi;
  done
- find $HOME/CACHE -name .starts | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.starts/} ]]; then cp -r $line $DIR; fi; done
- jdk_switcher use $JDK
cache:
  directories:
  - $HOME/.m2
  - $HOME/CACHE
dist: trusty
install: mvn -q -U install -DskipTests=true --settings /var/tmp/settings.xml
language: java
matrix:
  fast_finish: true
  include:
  - env: PHASE="-Ptravis,jdk18" JDK=openjdk8
  - env: PHASE="-Pmysql,jdk18" JDK=openjdk8
  - env: PHASE="-Ppostgresql,jdk18" JDK=openjdk8
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn -q -Djava.security.egd=file:/dev/./urandom -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
  -Dorg.slf4j.simpleLogger.log.org.killbill.billing.util.cache=ERROR -Dorg.slf4j.simpleLogger.log.org.killbill.billing.lifecycle=ERROR
  -Dlogback.configurationFile=$PWD/profiles/killbill/src/test/resources/logback.travis.xml
  clean install $PHASE -pl '!beatrix,!profiles,!profiles/killbill,!profiles/killpay'
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
